### ISSUE TITLE
PIMseq example 1

### ISSUE THREAD

**Issue by johannabult** [CenterForStatistics-UGent/PIMseq#3]
When I try to run (from example 1):

plotPIrank(res.PIM, contrast = 1, PI.thrld = c(0.3, 0.7))
title(main="Gene ranking based on PI")

I get the following error message: Error in testPIMcontrast(pim.res, contrasts = contrast) : Contrast should be a matrix class. Rows showd be contrasts and the number of columns should be equal to the number of coefficients in the model.

In addition, I was wondering if the output from "head(res.PIM$test.contrasts)" is correct:
![image](https://github.com/CenterForStatistics-UGent/PIMseq/assets/139330906/18df2635-cea8-494e-bf21-b741289f7575)
In the example data, there is only one condition (treatment) with options 0 and 1, but in the output from head(res.PIM$test.contrasts) the rownames are treatment, treatment1, treatment2 ... treatment5.

**Comment by AlemuTA** [comment]
The rownames are automatically added by R and you may ignore them. The genes are already on the ID column. I will check into this error asap.

**Comment by AlemuTA** [comment]
use `contrast = as.matrix(1)` for the contrast argument.

```
# rank genes based on their estimated PI  
plotPIrank(pim.res = res.PIM, contrast = as.matrix(1), PI.thrld = c(0.3, 0.7))
title(main="Gene ranking based on PI")
```

**Comment by AlemuTA** [comment]
all issues are fixed. Please check and confirm.

**Comment by johannabult** [comment]
Yes, this works. Thank you! 

For the testPIMcontrast() function: contrast1 <- testPIMcontrast(res.PIM, contrasts = c(1, 0)). I get the same error "Contrast should be a matrix class. Rows showd be contrasts and the number of columns should be equal to the number of coefficients in the model."

Is this fixable in a similar manner?

**Comment by AlemuTA** [comment]
Yes, it should work like this `contrast1 <- testPIMcontrast(res.PIM, contrasts = matrix(c(1, 0), nrow=1))`

**Comment by AlemuTA** [comment]
Yes, it should work like this `contrast1 <- testPIMcontrast(res.PIM, contrasts = matrix(c(1, 0), nrow=1))`

**Comment by johannabult** [comment]
I have a dataset with condition = c(0,1,2,3) (=factor). How can I apply the testPIMcontrast() function to compare for example conditon =0 with condition = 3? 

I have tried the following code, but this does not work:
contrast1 <- testPIMcontrast(res.PIM, contrasts = matrix(c(0,3), nrow=1))
_Error in FUN(X[[i]], ...) : 
  Number of columns of contrast matrix must match number of coefficients in fit_

**Comment by AlemuTA** [comment]
If your reference category is condition 0 when creating the dummy variables, then your contrast must be `matrix(c(0, 0, 1), nrow=1)`  to compare condition 3 to condition 0. That is,

`contrast1 <- testPIMcontrast(res.PIM, contrasts = matrix(c(0, 0, 1), nrow=1))` 

Let me know if this doesn't work.
